name: air_passenger_forecasting

channels:
  - defaults

dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - jupyter
  - pip
  - pip:
    - statsmodels
    - xgboost
    - pytest
